#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/hfsplus ] || exit 0

case $property in
    formatable)
	echo hfsplus
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    hfsplus)
		echo hfsplus
		;;
	esac
	;;
esac
